export const lightTokens = {
  primary:                '#006A60',
  onPrimary:              '#FFFFFF',
  primaryContainer:       '#9EF2E4',
  onPrimaryContainer:     '#00201C',
  secondary:              '#4A6360',
  onSecondary:            '#FFFFFF',
  secondaryContainer:     '#CCE8E4',
  onSecondaryContainer:   '#05201D',
  tertiary:               '#7D5700',       // Amber â COBOL amber terminal
  onTertiary:             '#FFFFFF',
  tertiaryContainer:      '#FFDEA4',
  onTertiaryContainer:    '#281800',
  error:                  '#BA1A1A',
  onError:                '#FFFFFF',
  errorContainer:         '#FFDAD6',
  onErrorContainer:       '#410002',
  background:             '#FAFDFC',
  onBackground:           '#191C1C',
  surface:                '#FAFDFC',
  onSurface:              '#191C1C',
  surfaceVariant:         '#DAE5E2',
  onSurfaceVariant:       '#3F4947',
  outline:                '#6F7977',
  outlineVariant:         '#BEC9C6',
  surfaceContainerLowest: '#FFFFFF',
  surfaceContainerLow:    '#F4F7F6',
  surfaceContainer:       '#EEF1F0',
  surfaceContainerHigh:   '#E8ECEB',
  surfaceContainerHighest:'#E3E6E5',
};

export const darkTokens = {
  primary:                '#82D5C8',
  onPrimary:              '#003731',
  primaryContainer:       '#004F48',
  onPrimaryContainer:     '#9EF2E4',
  secondary:              '#B1CCCA',
  onSecondary:            '#1C3533',
  secondaryContainer:     '#334B49',
  onSecondaryContainer:   '#CCE8E4',
  tertiary:               '#FFBA46',
  onTertiary:             '#422C00',
  tertiaryContainer:      '#5F4100',
  onTertiaryContainer:    '#FFDEA4',
  error:                  '#FFB4AB',
  onError:                '#690005',
  errorContainer:         '#93000A',
  onErrorContainer:       '#FFDAD6',
  background:             '#191C1C',
  onBackground:           '#E1E3E2',
  surface:                '#191C1C',
  onSurface:              '#E1E3E2',
  surfaceVariant:         '#3F4947',
  onSurfaceVariant:       '#BEC9C6',
  outline:                '#899390',
  outlineVariant:         '#3F4947',
  surfaceContainerLowest: '#131616',
  surfaceContainerLow:    '#191C1C',
  surfaceContainer:       '#1D2121',
  surfaceContainerHigh:   '#282B2B',
  surfaceContainerHighest:'#323636',
};
